export const HABITS_LIST_REQUEST = "HABITS_LIST_REQUEST";
export const HABITS_LIST_SUCCESS = "HABITS_LIST_SUCCESS";
export const HABITS_LIST_FAIL = "HABITS_LIST_FAIL";

export const HABITS_CREATE_REQUEST = "HABITS_CREATE_REQUEST";
export const HABITS_CREATE_SUCCESS = "HABITS_CREATE_SUCCESS";
export const HABITS_CREATE_FAIL = "HABITS_CREATE_FAIL";

export const HABITS_UPDATE_REQUEST = "HABITS_UPDATE_REQUEST";
export const HABITS_UPDATE_SUCCESS = "HABITS_UPDATE_SUCCESS";
export const HABITS_UPDATE_FAIL = "HABITS_UPDATE_FAIL";

export const HABITS_DELETE_REQUEST = "HABITS_DELETE_REQUEST";
export const HABITS_DELETE_SUCCESS = "HABITS_DELETE_SUCCESS";
export const HABITS_DELETE_FAIL = "HABITS_DELETE_FAIL";